config/routes.rb
Rails.application.routes.draw do
  resources :databases
 	get 'welcome/index'
	get 'messages/:id' => 'welcome#show'

	root 'welcome#index'
	post 'welcome/index' => 'welcome#create'

	post 'notes/api' => 'welcome#notesapi'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/database.rb
class Database < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  before_action :set_database, only: [:show, :edit, :update, :destroy]

  # GET /databases
  # GET /databases.json
  def index
    @databases = Database.all
  end

  # GET /databases/1
  # GET /databases/1.json
  def show
  end

  # GET /databases/new
  def new
    @database = Database.new
  end

  # GET /databases/1/edit
  def edit
  end

  # POST /databases
  # POST /databases.json
  def create
    @database = Database.new(database_params)

    respond_to do |format|
      if @database.save
        format.html { redirect_to @database, notice: 'Database was successfully created.' }
        format.json { render :show, status: :created, location: @database }
      else
        format.html { render :new }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /databases/1
  # PATCH/PUT /databases/1.json
  def update
    respond_to do |format|
      if @database.update(database_params)
        format.html { redirect_to @database, notice: 'Database was successfully updated.' }
        format.json { render :show, status: :ok, location: @database }
      else
        format.html { render :edit }
        format.json { render json: @database.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /databases/1
  # DELETE /databases/1.json
  def destroy
    @database.destroy
    respond_to do |format|
      format.html { redirect_to databases_url, notice: 'Database was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_database
      @database = Database.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def database_params
      params.require(:database).permit(:number, :data)
    end
end

app/controllers/welcome_controller.rb
require 'nokogiri'

MIN_ID = 10000
MAX_ID = 99999
$usedIDs = Array.new
$link = ""
$herokuURL = "https://secret-msg.herokuapp.com"
$message = ""

def get_id
	isPresent = false
	until isPresent
		isPresent = false
		@temp = rand(MIN_ID..MAX_ID)
		isPresent = true unless $usedIDs.include?(@temp)
	end
	$usedIDs.push(@temp.to_s)
	return @temp.to_s
end

def del(id)
	$usedIDs.delete(id.to_s)
	Database.destroy(id)
end

def new(text, id)
	if text == ""
		$message = "ERR: PROVIDE SOME TEXT"
		$usedIDs.delete(id.to_s)
		$link = ""
		return 0
	end
	unless id == nil
		a = Database.create(:data => text, :id => id.to_i)
		b = a.save
		unless b
			$message = "ERR: COULD NOT SAVE MESSAGE"
			redirect_back(fallback_location: root_path)
			return 0;
		end
	end
end

def read(iden)
	unless $usedIDs.include?(iden.to_s)
		$message = "ERR: NO MESSAGE WITH THIS ID"
		redirect_back(fallback_location: root_path)
		return 0
	end
	a = Database.find(iden.to_i)
	$message = a.send(:data)
	$link = ""
	redirect_back(fallback_location: root_path)
	del(iden.to_i)
end

class WelcomeController < ApplicationController
	protect_from_forgery unless: -> {request.format.json? }

	def index
	end

	def clear
		$link = ""
		$message = ""
	end

	def reset
		Database.delete_all
		$link = ""
		redirect_back(fallback_location: root_path)
	end
	
	def show
		id = params[:id]
		if id.to_i == -1
			reset
			return 0;
		end
		read(id)
	end

	def create
		clear
		text = params[:text]
		a = get_id
		$link = $herokuURL + "/messages/" + a
		new(text, a)
		redirect_back(fallback_location: root_path)
	end

	def notesapi
		type = request.headers["Content-Type"]
		uid = get_id
		$link = $herokuURL + "/messages/" + uid
		res = {"url" => $link}
		if type == "application/json"
			text = params[:message]
			render json: res
			
		elsif type == "text/xml"
			text = Nokogiri::XML.fragment(request.body.read).content
			render xml: res
		end	
		new(text, uid)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/databases_helper.rb
module DatabasesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/databases/_form.html.erb
<%= form_with(model: database, local: true) do |form| %>
  <% if database.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(database.errors.count, "error") %> prohibited this database from being saved:</h2>

      <ul>
      <% database.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :database_number %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data, id: :database_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/databases/edit.html.erb
<h1>Editing Database</h1>

<%= render 'form', database: @database %>

<%= link_to 'Show', @database %> |
<%= link_to 'Back', databases_path %>

app/views/databases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Databases</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @databases.each do |database| %>
      <tr>
        <td><%= database.number %></td>
        <td><%= database.data %></td>
        <td><%= link_to 'Show', database %></td>
        <td><%= link_to 'Edit', edit_database_path(database) %></td>
        <td><%= link_to 'Destroy', database, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Database', new_database_path %>

app/views/databases/new.html.erb
<h1>New Database</h1>

<%= render 'form', database: @database %>

<%= link_to 'Back', databases_path %>

app/views/databases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @database.number %>
</p>

<p>
  <strong>Data:</strong>
  <%= @database.data %>
</p>

<%= link_to 'Edit', edit_database_path(@database) %> |
<%= link_to 'Back', databases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp2</title>

    <style>
	.metro-over{
		border: none;
		outline: 0;
		background: none;
		color: white;
		font-weight: bold;
	}
	.metro{
		position:relative;
		display: inline-block;
		padding: 10px;
		margin: 10px;
		background: #08C;
		color: white;
		font-weight: bold;
		text-decoration: none;
		box-shadow:
			1px 1px #53A7EA,
			2px 2px #53A7EA,
			3px 3px #53A7EA;
		transition: all 0.1s ease-in;
	}
	.metro:hover{
		background: #0AF
	}
	.metro:active{
		box-shadow: none;
		top:3px;
		left:3px;
	}
	.depth{
		resize:none;
		display:block:
		border: 1px solid rgba(255,255,255,0.6);
		background: linear-gradient(#EEE, #FFF);
		transition: all 0.3s ease-out;
		box-shadow: inset 0 1px 4px rgba(0,0,0,0.4);
		padding: 5px;
		color: #555;
		width:100%;
	}
	.depth:focus{
		outline: none;
		background-position: 0 -1.7em;
	}

	.inline-link{
		display: inline-block;
		margin: 0 0.2em;
		padding: 3px;
		background: #97CAF2;
		border-radius: 2px;
		transition: all 0.3s ease-out;
		text-decoration: none;
		font-weight: bold;
		color:white;
	}
	.inline-link:hover{
		background: #53A7EA
	}
	.inline-link:active{
		background: #C4E1F8
	}
	.inline-link:empty{
		display:none;
	}
    </style>

    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<body style="background-image: linear-gradient(91deg, #0fb8ad 0%, #1fc8db 51%, #2cb5e8 75%); overflow:hidden;">
<div style="background-color: rgba(15,15,143,.25); text-align:center; color:White; font-family:Courier New; border-radius: 20px/60px"><h1>PrivNote Mock</h1></div>

<div style="backface-visibility:hidden">

<%= form_tag({}, multipart: true) do %>
	<div class="depth"><%= text_area_tag 'text', nil, rows:6, cols: 100, class:"depth" %><div>
	<p><div style="position:relative; display:inline; left:50%" class="metro"><%= submit_tag 'Get Link', class:"metro-over"%></div>
<% end %>
<p style="padding-bottom:1cm"><pre style="border-radius:25px">
	<h4 style="text-align:center"><a href="<%= $link.inspect[1..-2] %>", class="inline-link"><%= $link.inspect[1..-2] %></a></h4>
</pre>
<p><pre style="background-color:SkyBlue; border-radius:25px">
	<h5 style="text-align:center; font-family:Courier New"><%= $message.inspect[1..-2] %></h5>
</pre>
</div>